"""
phantom_toolkit/report.py
Generates a Markdown report from collected Findings — meant to be handed
to a dev team, with severity ranking and copy-pasteable fix guidance.
"""

import datetime

SEV_ORDER = ["HIGH", "MED", "LOW", "INFO", "OK"]
SEV_LABEL = {
    "HIGH": "🔴 High", "MED": "🟡 Medium", "LOW": "🔵 Low",
    "INFO": "ℹ️ Info", "OK": "✅ OK / No issue",
}


def generate_report(target_url, all_findings, output_path):
    by_sev = {s: [] for s in SEV_ORDER}
    for f in all_findings:
        by_sev.setdefault(f.severity, []).append(f)

    risk_score = sum({"HIGH": 5, "MED": 2, "LOW": 1}.get(f.severity, 0) for f in all_findings)

    lines = []
    lines.append(f"# Security Assessment Report")
    lines.append(f"\n**Target:** {target_url}")
    lines.append(f"**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Overall risk score:** {risk_score}")
    lines.append(f"\n> Authorized assessment. Recon-level automated scan — findings marked MED/HIGH "
                  f"should be manually verified before being treated as confirmed.\n")

    lines.append("## Summary\n")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for s in ["HIGH", "MED", "LOW"]:
        lines.append(f"| {SEV_LABEL[s]} | {len(by_sev.get(s, []))} |")
    lines.append("")

    for sev in ["HIGH", "MED", "LOW"]:
        items = by_sev.get(sev, [])
        if not items:
            continue
        lines.append(f"\n## {SEV_LABEL[sev]} Findings\n")
        for i, f in enumerate(items, 1):
            lines.append(f"### {i}. [{f.category}] {f.title}")
            lines.append(f"\n**Detail:** {f.detail}\n")
            if f.fix:
                lines.append(f"**Recommended fix:**\n```\n{f.fix}\n```\n")

    info_items = by_sev.get("INFO", [])
    if info_items:
        lines.append("\n## Informational\n")
        for f in info_items:
            lines.append(f"- **[{f.category}] {f.title}** — {f.detail}")

    ok_items = by_sev.get("OK", [])
    if ok_items:
        lines.append("\n## Checks with no issue found\n")
        for f in ok_items:
            lines.append(f"- [{f.category}] {f.title}")

    lines.append("\n---\n*Generated by PHANTOM-X toolkit — recon-level automated scan, "
                  "not a substitute for full manual review.*")

    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return output_path, risk_score
